# Generated by Django 3.2 on 2021-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
